name: Windows - Build and artifact

on:
  push:
    branches: [ 'main' ]
    tags: [ '*' ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Get zip
        uses: FoxtrotPerry/fetch-file-action@v0-alpha
        with:
          url: 'https://files.hk-modding.org/aesdk_oct21_win.zip'
          filename: 'aesdk_oct21_win.zip'

      - name: Unzip zip
        uses: hoatruongdev09/extract-zip-github-action@v1.2
        with:
          input-path: 'aesdk_oct21_win.zip'
          output-path: '${{ github.workspace }}/aesdk_oct21_win'

      #- name: Make boost dir
      #  run: mkdir boost
      #  shell: bash
      #  working-directory: ${{ github.workspace }}

      #- name: Set up boost
      #  id: boost-install
      #  uses: johnwason/vcpkg-action@v6
      #  with:
      #    pkgs: boost
      #    triplet: x64-windows-release

      - name: Set up boost
        id: boost-install
        run: vcpkg install boost:x64-windows-release
        shell: bash
        #working-directory: ?

      - name: Set up cuda
        id: cuda-install
        uses: Jimver/cuda-toolkit@v0.2.23
        with:
          cuda: '10.2.89'

      #- name: Set system envs
      #  run: |
      #    echo "CUDA_SDK_BASE_PATH=${{ steps.cuda-install.outputs.CUDA_PATH }}" >> $GITHUB_ENV
      #    echo "BOOST_BASE_PATH=${{ steps.boost-install.outputs.root }}" >> $GITHUB_ENV
      #  shell: bash
      #  #working-directory: ?

      - name: Set system envs
        run: |
          echo "CUDA_SDK_BASE_PATH=${{ steps.cuda-install.outputs.CUDA_PATH }}" >> $GITHUB_ENV
        shell: bash
        #working-directory: ?

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'main'
          path: 'aesdk_oct21_win/AfterEffectsSDK/Examples/ISF4AE'
          submodules: 'recursive'

      - name: Set more system envs
        run: |
          mkdir ../../../../__build
          echo "AE_PLUGIN_BUILD_DIR=../../../../__build" >> $GITHUB_ENV
          cp "VVISF-GL/external/GLEW/win_x64/glew32.dll" "/c/Windows/System32/" >> $GITHUB_ENV
          tr -d '\15\32' < VVISF-GL-Submodule.patch > VVISF-GL-Submodule.unix.patch
          git apply VVISF-GL-Submodule.unix.patch
        shell: bash
        working-directory: aesdk_oct21_win/AfterEffectsSDK/Examples/ISF4AE

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: 'x64'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build zip contents
        run: msbuild ISF4AE/Win/ISF4AE.sln
        #shell: bash
        working-directory: aesdk_oct21_win/AfterEffectsSDK/Examples

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Examples
          path: __build/*
